server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\music.db
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
music:
  base_path: E:/T/Music/
#  scan_path: E:/T/Music/2-Japanese/白色相簿
#  base_url: http://localhost:8088/music
  map_url: /music/**

#spring:
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/bili
#  datasource:
#    driver-class-file: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/bili?serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    lettuce:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 100ms